/**
 * LLM Transport — canonical interface for all LLM transports.
 *
 * Every transport implements provider-specific logic:
 * - Schema translation (AgentTool → provider-specific schema)
 * - Request building (headers, auth, body construction)
 * - Response parsing (extracting text and tool calls)
 * - Error normalization (HTTP errors → common error type)
 * - Usage normalization (provider-specific usage → common format)
 * - SSE event parsing (streaming responses)
 * - Model discovery (listing available models)
 *
 * @module agentRuntime/transport/LLMTransport
 */

export type TransportProviderKind = "openai" | "anthropic" | "gemini";

export interface TransportUsage {
  /** Number of tokens used for the prompt. */
  readonly inputTokens?: number | undefined;
  /** Number of input tokens that were cached (e.g., prompt caching). */
  readonly cachedInputTokens?: number | undefined;
  /** Number of tokens created for cache (Anthropic-specific). */
  readonly cacheCreationTokens?: number | undefined;
  /** Number of tokens generated by the model. */
  readonly outputTokens?: number | undefined;
  /** Number of tokens used for reasoning (extended thinking). */
  readonly reasoningOutputTokens?: number | undefined;
  /** Estimated cost in USD. */
  readonly providerCostUsd?: number | undefined;
}

export interface TransportHistoryEntry {
  readonly role: "user" | "assistant" | "tool" | "system";
  readonly content?: string | Array<Record<string, unknown>> | undefined;
  readonly toolCalls?:
    | ReadonlyArray<{
        readonly id: string;
        readonly name: string;
        readonly arguments: string;
      }>
    | undefined;
  readonly toolResults?:
    | ReadonlyArray<{
        readonly id: string;
        readonly name: string;
        readonly result: string;
      }>
    | undefined;
  readonly options?:
    | ReadonlyArray<{ readonly id: string; readonly value: string | boolean }>
    | undefined;
}

export interface TransportAttachment {
  readonly mimeType: string;
  readonly data: string;
}

export interface TransportRequest {
  readonly model: string;
  readonly text: string;
  readonly history: ReadonlyArray<TransportHistoryEntry>;
  readonly tools?:
    | ReadonlyArray<{
        readonly type: "function";
        readonly function: {
          readonly name: string;
          readonly description: string;
          readonly parameters: Record<string, unknown>;
        };
      }>
    | undefined;
  readonly stream?: boolean | undefined;
  readonly options?:
    | ReadonlyArray<{ readonly id: string; readonly value: string | boolean }>
    | undefined;
  readonly attachments?: ReadonlyArray<TransportAttachment> | undefined;
}

export interface TransportBuildInput {
  readonly request: TransportRequest;
  readonly baseUrl: string;
  readonly headers: Readonly<Record<string, string>>;
}

export interface TransportRequestPlan {
  readonly url: string;
  readonly headers: Record<string, string>;
  readonly body: Record<string, unknown>;
}

export interface TransportResponse {
  readonly text: string;
  readonly toolCalls: ReadonlyArray<TransportToolCall>;
}

export interface TransportToolCall {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
}

export interface TransportError {
  readonly message: string;
  readonly retryable: boolean;
  readonly status?: number | undefined;
  readonly code?: string | undefined;
}

export interface TransportStreamEvent {
  readonly kind: "text-delta" | "tool-call" | "tool-call-delta" | "usage" | "error" | "done";
  readonly text?: string | undefined;
  readonly toolCallId?: string | undefined;
  readonly toolName?: string | undefined;
  /** For OpenAI chunked tool arguments. */
  readonly toolArgumentsJson?: string | undefined;
  /** For Anthropic incremental tool arguments. */
  readonly toolArgumentsDelta?: string | undefined;
  /** Index of the tool call within the current response. */
  readonly toolCallIndex?: number | undefined;
  /** Stable item ID for the tool call (OpenAI Responses). */
  readonly toolItemId?: string | undefined;
  readonly usage?: TransportUsage | undefined;
  readonly error?: string | undefined;
}

export interface TransportModelRecord {
  readonly id: string;
  readonly name: string;
  readonly contextWindow?: number | undefined;
  readonly maxOutputTokens?: number | undefined;
}

export interface LLMTransport {
  /** Provider identifier for telemetry and routing. */
  readonly providerKind: TransportProviderKind;
  /** Build an HTTP request from a transport request. */
  readonly buildRequest: (input: TransportBuildInput) => TransportRequestPlan | undefined;
  /** Parse a non-streaming JSON response. */
  readonly parseResponse: (json: Record<string, unknown>) => TransportResponse;
  /** Parse an SSE event block into one or more stream events. */
  readonly parseSseEvents: (block: string) => ReadonlyArray<TransportStreamEvent>;
  /** Normalize an HTTP error response. */
  readonly normalizeError: (body: string, status: number) => TransportError;
  /** Normalize provider-specific usage into TransportUsage. */
  readonly normalizeUsage: (json: Record<string, unknown>) => TransportUsage | undefined;
  /** Build a request to list available models. */
  readonly buildDiscoveryRequest?: (input: TransportBuildInput) => TransportRequestPlan | undefined;
  /** Parse a model list response into canonical model records. */
  readonly normalizeModelList?: (
    json: Record<string, unknown>,
  ) => ReadonlyArray<TransportModelRecord>;
}
